server:
  service:
    type: LoadBalancer
  global:
    scrape_interval: 1s
extraScrapeConfigs: |
  - job_name: 'sample-job'
    scrape_interval: 1s
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - action: keep
        source_labels: [__meta_kubernetes_pod_container_name]
        regex: "prometheus-statsd"
   - job_name: 'test'
     kubernetes_sd_configs:
     - role: endpoints
     relabel_configs:
     - action: labelmap
       source_labels: [__meta_kubernetes_service_name]
       regex: react-hello-world
